version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  celery:
    build: .
    command: celery -A celery_worker worker --loglevel=info --pool=eventlet
    volumes:
      - .:/app
    depends_on:
      - redis