groups:
  - name: example-alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Высокая загрузка CPU на {{ $labels.instance }}"
          description: "CPU > 1% в течение 1 минуты."