route:
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: ''
        chat_id: 
        message: |
          🔴 АЛЕРТ: {{ .CommonAnnotations.summary }}
          {{ .CommonAnnotations.description }}