route:
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5m

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: ${{ env TELEGRAM_BOT_TOKEN}}
        chat_id: $({ env TELEGRAM_CHAT_ID}}
        message: |
          [ALERT] {{ .CommonAnnotations.summary }}
          Severity: {{ .CommonLabels.severity }}
          Instance: {{ .CommonLabels.instance }}