version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - backend

  celery:
    build: .
    container_name: celery_worker
    command: ["python", "celery_worker.py"]
    depends_on:
      - redis
      - rabbitmq
      - db
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Web UI
    networks:
      - backend

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
